export const projects = {
  pokedex: {
    title: "Pokedex",
    content: "Consumiendo Api de Pokemon",
    img: "/captureprojects/pokeapi.png",
    url: "https://poke-apifr.netlify.app/",
    github: "https://github.com/fred0727/pokeapi-app",
    codes: ["html", "js", "reactjs", "tailwind", "vite"],
  },
  academlostore: {
    title: "Academlo Store",
    content: "Proyecto Store de Academlo",
    img: "/captureprojects/academlostore.png",
    url: "https://academlostorefr.netlify.app/",
    github: "https://github.com/fred0727/cart-academlo",
    codes: ["html", "js", "css3"],
  },
  rickandmorty: {
    title: "Rick and Morty App",
    content: "Consumiento la API de Rick and Morty",
    img: "/captureprojects/rickandmortyapp.png",
    url: "https://rickandmortyfr.netlify.app/",
    github: "https://github.com/fred0727/rickandmortyapp-academlo",
    codes: ["html", "js", "reactjs", "tailwind", "vite"],
  },
  weatherapp: {
    title: "Weathe App",
    content: "Consumiendo la API de OpenWeather",
    img: "/captureprojects/weatherapp.png",
    url: "https://weatherappreactfr.netlify.app/",
    github: "https://github.com/fred0727/weatherapp-react-academlo",
    codes: ["html", "js", "reactjs", "tailwind", "vite"],
  },
  pharserandom: {
    title: "Pharse Random",
    content: "Frases y fondo random celebres",
    img: "/captureprojects/infogalax.png",
    url: "https://phraserandomfr.netlify.app/",
    github: "https://github.com/fred0727/phraserandom-academlo",
    codes: ["html", "js", "reactjs", "vite"],
  },
  fraremsac: {
    title: "Frarem",
    content: "Landing Page modelo para una empresa",
    img: "/captureprojects/frarem.png",
    url: "https://frarem-sacfr.netlify.app/",
    github: "https://github.com/fred0727/fraremsac",
    codes: ["html", "js", "css3", "php"],
  },
};
